### ISSUE TITLE
Creatures sometimes fail to Warp.

### ISSUE THREAD

**Issue by KeyboardInterrupt** [AlbianWarp/AlbianWarpGameModifications#6]
Sometimes Creatures cannot be warped again, if they already inhabitated the world before.

![](https://i.imgur.com/LBAxx15.jpg)

![](https://i.imgur.com/12fVANZ.jpg)

This needs further testing, to pin down the exact circumstances that lead to this Problem.

**Comment by KeyboardInterrupt** [comment]
Verm: So the first problem was that he went through the portal unnamed, came back named, and didn't get a new file

**Comment by KeyboardInterrupt** [comment]
probably relates to: https://github.com/AlbianWarp/AlbianWarpClient/issues/10

**Comment by Amaikokonut** [comment]
Hmm yeah I suspect that this has to do with the game not wanting to export/warp a creature with a moniker matching one already on disk. I think removing warped out creature files will probably fix most of those issues but we should probably make the game display a visible error message somewhere when this is happening (since it would also probably happen if you exported a creature, then the world crashed and rolled back, and then you tried to warp out the same creature)

**Comment by KeyboardInterrupt** [comment]
We could base the error messages on the `SystemMessageAgent` system we planed to implement.

Lets say we encounter an error like this, we could then inject an SMA containing information about the error into the game.

Something like this:

```
new simp 1 1 357XX  "blnk" 1 0 0
setv name "sma_type" 1
setv name "error_type" 3
sets name "message" "Creature <NAME>/<MONIKER> could not be uploaded!"
sets name "moniker" <MONIKER>"
sets name "name" "<NAME>"
```

**Comment by KeyboardInterrupt** [comment]
I think this is fixed with the latest SCA Changes. We can reopen this Issue if that turns out to be false.
